spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: SpringBootDB369
    url: jdbc:postgresql://db.xrizljdyaoyvzcavgbol.supabase.co:5432/postgres
  thymeleaf:
    mode: HTML
  jpa:
    # hibernate:
    #   ddl-auto: create
    show-sql: true
  # mvc:
  #   view:
  #       prefix: /WEB-INF/jsp/
  #       suffix: .jsp
  # profiles:
  #   active: prod
logging:
  root: WARN
  level:
    org:
      springframework: DEBUG
  # file: logs/logs.log
book:
  name: 書本一號